### ISSUE TITLE
Research on JMonkey game engine

### ISSUE THREAD

**Issue by gauravchodwadia** [CMPE202-TEAM03-SPRING16/GameWithDesignPattern#4]
Based on research by Gaurav, an option to chose the game development environment is JMonkey. Chirag will dig deep and come up with pros and cons of using JMonkey.

**Comment by chirag-orbittec** [comment]
Some reference links

http://stackoverflow.com/questions/21616995/should-i-use-jmonkeyengine-3-jme-3-or-unity-4-3-to-teach-game-programming-to-m

https://jmonkeyengine.org/301602/in-the-age-of-free-aaa-game-engines-are-we-still-relevant/

**Comment by chirag-orbittec** [comment]
Found that JMonkey is an Open -source Game Engine based on java, we should support Open Source projects.
