### ISSUE TITLE
Research on Unity 3D game engine

### ISSUE THREAD

**Issue by gauravchodwadia** [CMPE202-TEAM03-SPRING16/GameWithDesignPattern#5]
Based on research by Gaurav, an option to chose the game development environment is Unity3D. Darshan will dig deep and come up with pros and cons of using Unity3D.

**Comment by darshanmodh** [comment]
http://docs.unity3d.com/Manual/index.html

**Comment by darshanmodh** [comment]
~ Collect information of Unity3D's system requirement
~ Install Unity3D in local system
